kind: Deployment
apiVersion: apps/v1
metadata:
  name: gateway
  namespace: app12
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: gateway
          env:
            - name: LOG_URL
              value: https://loger.sirafgroup.com/api/save-log
            - name: CACHE_TIME
              value: 36000
            - name: CACHE_IP_ADDRESS
              value: cache
          securityContext:
            runAsUser: 0
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          image: 'reg.masafiranian.ir/app12/gateway:0.1'
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: runasroot
      serviceAccount: runasroot
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
