#version: '3.10'
#
#services:
#  getway:
#    container_name: getway_webts
#    build:
#      context: .
#      dockerfile: Dockerfile
#    env_file:
#      - .env
#    volumes:
#      - .:/app
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - "80:80"
#    networks:
#      - network_api
#
#  cache:
#    image: docker.arvancloud.ir/memcached
#    networks:
#      - network_api
#    entrypoint:
#      - memcached
#      - -m
#      - "1264"
#
#networks:
#  network_api:
#    driver: overlay
#    external: true

services:
  app:
    image: ${DOCKER_REG}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${IMAGE_TAG}
    container_name: gateway_webts
    ports:
      - "6006:80"
    networks:
      - network_api
    env_file:
      - .env
    extra_hosts:
      - "minio.basynergy.ir:45.82.138.127"


  cache:
    image: docker.arvancloud.ir/memcached
    #    ports:
    #      - "11211:11211"
    networks:
      - network_api
    entrypoint:
      - memcached
      - -m 1264

networks:
  network_api:
    driver: bridge
    external: true

